using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;
using System;

namespace Fintex.Investments
{
    /// <summary>
    /// Records the actual simulated fill generated by a paper order.
    /// </summary>
    public class PaperTradeFill : FullAuditedAggregateRoot<long>, IMayHaveTenant
    {
        public const int MaxSymbolLength = 32;

        protected PaperTradeFill()
        {
        }

        public PaperTradeFill(
            int? tenantId,
            long userId,
            long accountId,
            long orderId,
            long? positionId,
            string symbol,
            AssetClass assetClass,
            MarketDataProvider provider,
            TradeDirection direction,
            decimal quantity,
            decimal price,
            decimal realizedProfitLoss,
            DateTime executedAt)
        {
            if (userId <= 0)
            {
                throw new ArgumentException("User id must be provided.", nameof(userId));
            }

            TenantId = tenantId;
            UserId = userId;
            AccountId = accountId;
            OrderId = orderId;
            PositionId = positionId;
            Symbol = NormalizeSymbol(symbol);
            AssetClass = assetClass;
            Provider = provider;
            Direction = direction;
            Quantity = EnsurePositive(quantity, nameof(quantity));
            Price = EnsurePositive(price, nameof(price));
            RealizedProfitLoss = realizedProfitLoss;
            ExecutedAt = executedAt;
        }

        public int? TenantId { get; set; }

        public long UserId { get; protected set; }

        public long AccountId { get; protected set; }

        public long OrderId { get; protected set; }

        public long? PositionId { get; protected set; }

        public string Symbol { get; protected set; }

        public AssetClass AssetClass { get; protected set; }

        public MarketDataProvider Provider { get; protected set; }

        public TradeDirection Direction { get; protected set; }

        public decimal Quantity { get; protected set; }

        public decimal Price { get; protected set; }

        public decimal RealizedProfitLoss { get; protected set; }

        public DateTime ExecutedAt { get; protected set; }

        private static string NormalizeSymbol(string symbol)
        {
            if (string.IsNullOrWhiteSpace(symbol))
            {
                throw new ArgumentException("Symbol is required.", nameof(symbol));
            }

            var normalized = symbol.Trim().ToUpperInvariant();
            if (normalized.Length > MaxSymbolLength)
            {
                throw new ArgumentException("Symbol is too long.", nameof(symbol));
            }

            return normalized;
        }

        private static decimal EnsurePositive(decimal value, string name)
        {
            if (value <= 0m)
            {
                throw new ArgumentOutOfRangeException(name, "Value must be greater than zero.");
            }

            return value;
        }
    }
}
