"use client";

import { createStyles } from "antd-style";

export const useStyles = createStyles(({ token }) => ({
  page: {
    height: "100vh",
    overflow: "hidden",
    padding: "20px",
    background:
      "radial-gradient(circle at top left, rgba(82,196,26,0.12), transparent 32%), radial-gradient(circle at top right, rgba(24,144,255,0.14), transparent 30%), linear-gradient(180deg, #07131f 0%, #071828 100%)",
    [`@media (max-width: ${token.screenLG}px)`]: {
      height: "auto",
      minHeight: "100vh",
      overflow: "visible",
      padding: "20px 16px 32px",
    },
  },
  shell: {
    maxWidth: 1640,
    margin: "0 auto",
    height: "calc(100vh - 40px)",
    [`@media (max-width: ${token.screenLG}px)`]: {
      height: "auto",
    },
  },
  academyGrid: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: "280px minmax(0, 1fr) 340px",
    gridTemplateRows: "auto minmax(0, 1fr)",
    height: "100%",
    minHeight: 0,
    [`@media (max-width: ${token.screenLG}px)`]: {
      display: "block",
      height: "auto",
    },
  },
  leftRail: {
    gridColumn: "1 / 2",
    gridRow: "1 / 3",
    minHeight: 0,
    display: "flex",
  },
  rightRail: {
    gridColumn: "3 / 4",
    gridRow: "1 / 3",
    minHeight: 0,
    display: "flex",
    [`@media (max-width: ${token.screenLG}px)`]: {
      marginTop: 20,
    },
  },
  centerHeader: {
    gridColumn: "2 / 3",
    gridRow: "1 / 2",
    minWidth: 0,
  },
  centerStage: {
    gridColumn: "2 / 3",
    gridRow: "2 / 3",
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehavior: "contain",
    paddingRight: 8,
    [`@media (max-width: ${token.screenLG}px)`]: {
      overflow: "visible",
      paddingRight: 0,
      marginTop: 20,
    },
  },
  heroCard: {
    borderRadius: 18,
    background: "rgba(4, 18, 33, 0.88)",
    border: "1px solid rgba(255,255,255,0.08)",
    boxShadow: "0 14px 36px rgba(0,0,0,0.2)",
  },
  heroTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  heroTitle: {
    color: "#f5fbff",
    marginBottom: 0,
    fontSize: 24,
  },
  heroSteps: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    [`@media (max-width: ${token.screenMD}px)`]: {
      gridTemplateColumns: "1fr",
    },
  },
  heroStep: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
    padding: "10px 12px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.02)",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  heroStepActive: {
    background: "rgba(22,119,255,0.12)",
    borderColor: "rgba(22,119,255,0.28)",
  },
  heroStepNumber: {
    width: 28,
    height: 28,
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(232,241,248,0.74)",
    background: "rgba(255,255,255,0.06)",
    flexShrink: 0,
  },
  heroStepNumberActive: {
    background: "rgba(82,196,26,0.22)",
    color: "#dfffe6",
  },
  heroStepLabel: {
    color: "rgba(232,241,248,0.72)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  heroStepLabelActive: {
    color: "#f5fbff",
  },
  progressCard: {
    borderRadius: 20,
    background: "rgba(7, 24, 43, 0.88)",
    border: "1px solid rgba(255,255,255,0.06)",
    boxShadow: "0 16px 50px rgba(0,0,0,0.22)",
    height: "100%",
    overflowY: "auto",
    [`@media (max-width: ${token.screenLG}px)`]: {
      height: "auto",
      overflowY: "visible",
    },
  },
  progressStats: {
    display: "grid",
    gap: 16,
    marginBottom: 20,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    [`@media (max-width: ${token.screenMD}px)`]: {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  workspaceCard: {
    borderRadius: 22,
    background: "rgba(7, 24, 43, 0.9)",
    border: "1px solid rgba(255,255,255,0.06)",
    boxShadow: "0 20px 70px rgba(0,0,0,0.24)",
  },
  sidebarCard: {
    borderRadius: 22,
    background: "rgba(4, 16, 29, 0.92)",
    border: "1px solid rgba(255,255,255,0.06)",
    height: "100%",
    overflowY: "auto",
    [`@media (max-width: ${token.screenLG}px)`]: {
      width: "100%",
      height: "auto",
      overflowY: "visible",
    },
  },
  sidebarHeader: {
    marginBottom: 14,
  },
  sidebarTitle: {
    color: "#f5fbff",
    marginBottom: 6,
  },
  sidebarCopy: {
    color: "rgba(232,241,248,0.72)",
    marginBottom: 12,
  },
  sidebarSnapshot: {
    marginTop: 14,
    padding: 14,
    borderRadius: 16,
    background: "rgba(255,255,255,0.02)",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  sidebarSnapshotLabel: {
    display: "block",
    fontSize: 12,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "rgba(232,241,248,0.56)",
    marginBottom: 6,
  },
  sidebarSnapshotValue: {
    display: "block",
    color: "#f5fbff",
    fontWeight: 600,
  },
  quizUnlockBox: {
    marginTop: 14,
    padding: 14,
    borderRadius: 16,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.06)",
  },
  quizUnlockTop: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  quizUnlockCopy: {
    color: "rgba(232,241,248,0.7)",
    marginBottom: 0,
  },
  sectionCard: {
    borderRadius: 18,
    background: "rgba(7, 24, 43, 0.88)",
    border: "1px solid rgba(255,255,255,0.06)",
  },
  stageHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "flex-start",
    marginBottom: 16,
  },
  stageEyebrow: {
    color: "rgba(110,193,255,0.82)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontSize: 12,
  },
  stageTitle: {
    color: "#f5fbff",
    marginTop: 6,
    marginBottom: 4,
    fontSize: 26,
  },
  stageCopy: {
    color: "rgba(232,241,248,0.78)",
    maxWidth: 760,
    marginBottom: 0,
  },
  stageBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 14px",
    borderRadius: 999,
    color: "#d6e8ff",
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.06)",
  },
  lessonBody: {
    display: "grid",
    gap: 12,
  },
  lessonParagraph: {
    marginBottom: 0,
    padding: 16,
    borderRadius: 16,
    color: "rgba(232,241,248,0.84)",
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.05)",
  },
  lessonFooter: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "center",
    marginTop: 28,
    flexWrap: "wrap",
  },
  quizSummary: {
    display: "grid",
    gap: 12,
    marginBottom: 20,
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    [`@media (max-width: ${token.screenMD}px)`]: {
      gridTemplateColumns: "1fr",
    },
  },
  badgeRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 12,
  },
  resultCard: {
    borderRadius: 16,
    padding: 16,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.06)",
  },
  quizQuestionCard: {
    padding: 20,
    borderRadius: 18,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.06)",
  },
  quizRadioGroup: {
    width: "100%",
  },
}));
