using System;

namespace Fintex.Investments.PaperTrading.Dto
{
    /// <summary>
    /// Simulated fill generated by a paper order execution.
    /// </summary>
    public class PaperTradeFillDto
    {
        public long Id { get; set; }

        public long AccountId { get; set; }

        public long OrderId { get; set; }

        public long? PositionId { get; set; }

        public string Symbol { get; set; }

        public AssetClass AssetClass { get; set; }

        public MarketDataProvider Provider { get; set; }

        public TradeDirection Direction { get; set; }

        public decimal Quantity { get; set; }

        public decimal Price { get; set; }

        public decimal RealizedProfitLoss { get; set; }

        public DateTime ExecutedAt { get; set; }
    }
}
